"use client";

interface DocumentPreviewProps {
  title: string;
  content: string;
  onDownload?: () => void;
  onSend?: () => void;
}

export function DocumentPreview({
  title,
  content,
  onDownload,
  onSend,
}: DocumentPreviewProps) {
  return (
    <div className="card space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-500/10">
            <svg
              width="20"
              height="20"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              className="text-indigo-400"
            >
              <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
              <polyline points="14 2 14 8 20 8" />
            </svg>
          </div>
          <div>
            <h4 className="text-base font-semibold text-foreground">{title}</h4>
            <p className="text-xs text-muted-foreground">
              Generated by AI · Ready for review
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={onDownload}
            className="btn-ghost text-sm"
            title="Download"
          >
            <svg
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
              <polyline points="7 10 12 15 17 10" />
              <line x1="12" y1="15" x2="12" y2="3" />
            </svg>
            Download
          </button>
          <button onClick={onSend} className="btn-primary text-sm">
            <svg
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <line x1="22" y1="2" x2="11" y2="13" />
              <polygon points="22 2 15 22 11 13 2 9 22 2" />
            </svg>
            Send to Client
          </button>
        </div>
      </div>

      {/* Content preview */}
      <div className="rounded-xl border border-border-subtle bg-white/[0.02] p-4">
        <pre className="whitespace-pre-wrap font-sans text-sm text-muted-foreground leading-relaxed">
          {content}
        </pre>
      </div>
    </div>
  );
}
